#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
filters=$(cat "$DIR/filter.txt" | tr '\n' '|')
source $DIR/functions.sh

grep -vE '\"' \
  | grep -vE $filters \
  | perl -lpe ';s/http:\/\/dbpedia.org\/resource\//dbpedia:/g' \
  | perl -lpe ";s/ /$sep/g"
