#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source $DIR/aliases.env

hdtSearch -q "? ? ?" $1 2> /dev/null\
	| parallel --pipe -j$(nproc) --round-robin --block 1M $DIR/clean_line\
	| lbzip2 -zc > $2
