#!/usr/bin/env bash

hdtSearch -q "? ? ?" $1 2> /dev/null\
	| parallel --pipe cut -d \' \' -f1,3\
	| parallel --pipe tr \' \' \'\\n\'\
	| parallel --pipe sed -n '/^http/p'\
	| sort -u\
	|	lbzip2 -zc > $2
