#!/usr/bin/env bash
input="$1"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source $DIR/aliases.env

lbzcat $1 \
  | parallel --pipe -j$(nproc) --round-robin --block 1M $DIR/clean_line \
  | lbzip2 -zc > $2
