#!/usr/bin/env bash

# 1 row csv
# 2 mapping nodes
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

temp_file_1=$(mktemp)

lbzcat $1 \
  | parallel --pipe -j$(nproc) --round-robin --block 1M $DIR/get_abstract \
  | LC_ALL=C sort -u --parallel=8 > $temp_file_1


