#!/usr/bin/env bash

temp_file_1=$(mktemp)
temp_file_2=$(mktemp)
temp_file_3=$(mktemp)

lbzcat $1 \
  | cut -d'|' -f1 \
  | LC_ALL=C sort -u --parallel=8 > $temp_file_1
lbzcat $1 \
  | cut -d'|' -f3 \
  | LC_ALL=C sort -u --parallel=8 > $temp_file_2
cat $temp_file_1 $temp_file_2 \
  | LC_ALL=C sort -u --parallel=8 > $temp_file_3
paste -d'|' <(seq 0 $(wc -l < $temp_file_3)) <(cat $temp_file_3) \
  | lbzip2 -zc > $2
rm $temp_file_1 $temp_file_2 $temp_file_3
