#!/usr/bin/env bash

#1 triples
#2 filtered triples

triples=$1
filered_triples=$2
mapping_nodes=$3
mapping_rel=$4
adjacency=$5
text=$6

./filter $triples $filtered_triples
./gen_mapping_nodes $filtered_triples $mapping_nodes
./gen_mapping_relations $filtered_triples $mapping_rel
./set_ids $filtered_triples $mapping_nodes $mapping_rel $adjacency
./gen_text $mapping_nodes $text
