#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
hdtfile=$1
mapping=$2
outfile=$3

lbzcat $mapping \
  | parallel -j$(nproc) $DIR/get_name $hdtfile \
  | sort -t '|' -n -k 1 \
  | lbzip2 -zc > $outfile
