#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source $DIR/aliases.env
source $DIR/functions.sh
temp_file_1=$(mktemp)
temp_file_2=$(mktemp)
temp_file_3=$(mktemp)

lbzcat $1 \
  | cut -d"$sep" -f1 \
  | LC_ALL=C sort -u --parallel=8 > $temp_file_1
lbzcat $1 \
  | cut -d"$sep" -f3 \
  | LC_ALL=C sort -u --parallel=8 > $temp_file_2
cat $temp_file_1 $temp_file_2 \
  | LC_ALL=C sort -u --parallel=8 > $temp_file_3
length_ids=$(wc -l < $temp_file_3)
max_id=$(($length_ids-1))
paste -d"$sep" <(seq 0 $max_id) <(cat $temp_file_3) \
  | lbzip2 -zc > $2
rm $temp_file_1 $temp_file_2 $temp_file_3
