#!/usr/bin/env bash

temp_file_1=$(mktemp)
temp_file_2=$(mktemp)

awk -F"|" 'NR==FNR {m[$2]=$1;next};{print m[$1]"|"m[$3]}' <(lbzcat $2) <(lbzcat $1) > $temp_file_1
awk -F"|" 'NR==FNR {m[$2]=$1;next};{print m[$2]}' <(lbzcat $3) <(lbzcat $1) > $temp_file_2

pr -mts'|' "$temp_file_1" "$temp_file_2" \
  | lbzip2 -zc > $4
rm $temp_file_1 $temp_file_2
